
CREATE TABLE IF NOT EXISTS Workouts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    trainer VARCHAR(120) NOT NULL,
    gym VARCHAR(255) NOT NULL,
    date VARCHAR(255) NOT NULL,
    duration VARCHAR(255) NOT NULL,
    muscle VARCHAR(255) NOT NULL
);